# احمد سمير عوض
# 20211089
# رياضة و حاسب

# minimum edit distance algorithm

In [1]:
import numpy as np

In [2]:
def min_ed_dis(target,source):
    # min_ed_dis minmum edit distance
    # target,correct word
    # source: written word
    
    target = [k for k in target]
    source = [k for k in source]
    sol= np.zeros((len(source),len(target)))
    
    # first row and column 
    sol[0]=[j for j in range(len(target))]
    sol[:,0] = [j for j in range(len(source))]
    
    # add anchor value 
    if target[1]!= source[1]:
        sol[1,1] = 2       
        
    # fill in rest
    
    # through every column
    for c in range(1,len(target)):
        # through every row
        for r in range(1,len(source)):
            if target[c] != source[r]:
                min(sol[r-1,c],sol[r,c-1])+1
            else:
                sol[r,c]=sol[r-1,c-1]
    print("Edit distance matrix:")
    print(sol)
    print("-"*50)
    print("minumum edit distance is:",sol[len(source)-1,len(target)-1])

In [3]:
min_ed_dis("#bcde","#de")

Edit distance matrix:
[[0. 1. 2. 3. 4.]
 [1. 2. 0. 2. 0.]
 [2. 0. 0. 0. 2.]]
--------------------------------------------------
minumum edit distance is: 2.0
